[tool.poetry]
name = "nanogpt"
version = "0.1.0"
description = "Implementation of GPT in pytorch"
authors = ["martinabeleda <martin.abeleda@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.13.1"
wandb = "^0.13.9"
jupyter = "^1.0.0"
requests = "^2.28.2"
loguru = "^0.6.0"
numpy = "^1.24.1"
pandas = "^1.5.3"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
ruff = "^0.0.228"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
