[tool.poetry]
name = "nanogpt"
version = "0.1.0"
description = "Implementation of GPT in pytorch"
authors = ["martinabeleda <martin.abeleda@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.13.1"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
ruff = "^0.0.228"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
